version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      args:
        MYSQL_DATABASE : ${MYSQL_DATABASE}
        MYSQL_USER : $MYSQL_USER
        MYSQL_PASSWORD : $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD : $MYSQL_ROOT_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      args:
        MYSQL_DATABASE : "${MYSQL_DATABASE}"
        MYSQL_USER : "${MYSQL_USER}"
        MYSQL_PASSWORD : "${MYSQL_PASSWORD}"
        MYSQL_HOST : "${MYSQL_HOST}"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - network

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    networks:
      - network
    env_file:
      - .env

networks:
  network:
    name: network
    external: false

volumes:
  wordpress:
  mariadb: