version: '3.8'

services:
  nginx:
    container_name: nginx42
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    # restart: always
    networks:
      - network
    env_file:
      - .env

  mariadb:
    container_name: mariadb42
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    # restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress42
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - network

networks:
  network:
    name: network
    external: false

volumes:
  wordpress:
  mariadb: