version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    restart: always

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - network
    restart: always

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge

volumes:
  wordpress:
  mariadb: