version: '3'

services:
  mariadb:
    container_name: mariadb
    env_file: .env
    build: 
      context: requirements/mariadb
      args:
        MYSQL_DATABASE : ${MYSQL_DATABASE}
        MYSQL_USER : $MYSQL_USER
        MYSQL_PASSWORD : $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD : $MYSQL_ROOT_PASSWORD
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - network
    # restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      args:
        MYSQL_DATABASE : "${MYSQL_DATABASE}"
        MYSQL_USER : "${MYSQL_USER}"
        MYSQL_PASSWORD : "${MYSQL_PASSWORD}"
        MYSQL_HOST : "${MYSQL_HOST}"
    # restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - network

  nginx:
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    # restart: always
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  wordpress:
  mariadb: